### ISSUE TITLE
We need backups for all attributes that are entered into the game

### ISSUE THREAD

**Issue by RVNJ** [phoenixanimations/TheNuwasFile#15]
What he said

"Make it so you can also drag the backup attributes to the piece of equipment and the item will make a copy of it." - Tristan (AKA Gronto Billa[r]do), 2018

**Comment by phoenixanimations** [comment]
The solution is equip the character sheet with another character sheet. 

So example:

`Backup Attribute:`
Stat `Example Stat`: 1
Attribute `Example Attribute`: Add 1 to total damage.

`Example Weapon`
Equip (actually equip) Backup Attribute (which is actually a character sheet).

**Comment by RVNJ** [comment]
it has been done

**Comment by RVNJ** [comment]
derp re-opened it LOL
