### ISSUE TITLE
Attributes need access to the state machine.

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#27]
+ [ ] for number of attacks to reroll.
+ [ ] for attack hit/miss branch in the attack code.

**Comment by RVNJ** [comment]
I assume we can do this with the nodes being able to run other nodes? Could probably merge this issue with #41 and close it, yeah?

**Comment by RVNJ** [comment]
gotcha; explained over phone call

**Comment by phoenixanimations** [comment]
f06f7d7b52117570adc2a360413d275a79e11ff7 closes this
