### ISSUE TITLE
Have a state node that has the verb this.

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#34]
For example this weapon, instead of selecting a specific weapon.

**Comment by RVNJ** [comment]
Has my definitive approval

I assume this would also apply to characters since we use the same, uh, 'sheet' if you will

👍

**Comment by phoenixanimations** [comment]
Yes it would 👍, I'll try to figure out as it will be really useful for attributes running other attributes.
