### ISSUE TITLE
Make an attributes that calculate resistance.

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#37]
I suggest split it up into three categories 
+ [ ] Calculate melee resistance.
+ [ ] Calculate magic resistance.
+ [ ] Calculate archery resistance.

All this will do is grab class resistance from the enemy's class resistance. So for a melee weapon, the calculate magic/archery will be disabled.

Then on a shield/armor/weapon it will have the passive:
+ [ ] Add melee resistance to character resistance.
+ [ ] Add magic resistance to character resistance.
+ [ ] Add archery resistance to character resistance.

**Comment by RVNJ** [comment]
Tagging you onto this as well because we need to discuss what weapons are capable of touching

**Comment by RVNJ** [comment]
Fairly certain this one is complete. Will unlock if it falls apart.
