### ISSUE TITLE
Put resistance bonuses in on the player other characters.

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#38]
+ [ ] Melee Resistance Bonus
+ [ ] Magic Resistance Bonus
+ [ ] Archery Resistance Bonus

Possibly close this issue. We might solve this problem by just adding defects (as bonuses). And resistance will be reset by evaluate bonuses, armor/shields will re-add the numbers.

**Comment by RVNJ** [comment]
Forgot to do this one tonight. I'll try to add them in tomorrow.

**Comment by phoenixanimations** [comment]
Sure, I like the "soon" label. Definitely a useful alternative to urgent.
