### ISSUE TITLE
Combat Formula Node

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#42]

**Comment by RVNJ** [comment]
Since you've made a new node, I'll have to explain the process for it (tomorrow or Sunday, likely)

Reopening this since (based on your previous message) the node needs a slight tweak to it.

**Comment by phoenixanimations** [comment]
Makes sense.

**Comment by phoenixanimations** [comment]
Continuing our conversation from #36 I assume these are the correct numbers:

1, 1, 1, 1 = 1

**Comment by phoenixanimations** [comment]
Also I just looked at the character sheets for the combat level node. And god damn dood, you went all out.

Now I just imagine every time you hear "combat formula" this starts playing in your head: "I don't ever wanna feel like I did that day... Take me to the place I love, take me far away".

**Comment by RVNJ** [comment]
#1: 18 (correct)
#2: CBL should be 31
#3: 33 (correct)

**Comment by RVNJ** [comment]
Just ran the node formula in Unity and got the correct value for #2 so that appears to just be a typo.

👍

**Comment by phoenixanimations** [comment]
Once again closing this as da5ce9fc should fix this
