### ISSUE TITLE
Status descriptions

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#49]
+ [x] **Burn: static x% Damage per turn, can be removed by walking into Water**/some kind of Water Spell usage on self (Dev: unsure of spell-usage mechanics as of yet)
+ [x] **Poison: ~static~ dynamic x% Damage increasing as health depletes, can be removed by drinking an Antidote potion**
+ [x] Slow: **either** -x% Accuracy **or** -1 Movement
+ [x] **Stun: no Energy is gained when Attacking (Dev: does not prevent Ability usage)**
+ [x] **Shock: take 10% Recoil Damage when Attacking Target** (Dev: may add random element of 0-20%)
+ [x] **Bleed: 20% of all Non-Critical Damage dealt is calculated as Bleed Damage, which is applied once per turn, over 5 turns, subsequent 'Bleed'-based Damages will override existing Bleeds and reset the 5 turn timer**
+ [x] **Bind: Target cannot move for 1 turn, Bind-Immune for 2 turns following activation** (may remove/reduce Immunity)
+ [x] **Numb: -1 to _all_ Levels per turn**
+ [x] **~Corruption:~**
+ [x] **Drunk: +10% Damage, -20% Accuracy (Drunk isn't inherently a _Defect_ per se, just a Status**
+ [x] **Virus: Any and all Defects (not Statuses) attached to character are shared with adjacent characters**
+ [x] **Venom: Some form of automatic-KO - we will have to discuss this one to find a fair usage solution since it seems like a 10-Turn KO is what we have at the moment**

**Save For 2**
+ [x] **Frozen: Supposedly 'freezes' Defects in place, causing them to last 1 turn longer - something related to a Bind effect may be preferred however, or it could do both, but I feel like this one is a little complicated with how our Statuses work now**

> **emboldened** text is definitive, any other text is up for interpretation/debate/whatever
> -- Raven

**Comment by RVNJ** [comment]
edited post with known data

**Comment by phoenixanimations** [comment]
Great added it to github's [wiki](https://github.com/phoenixanimations/TheNuwasFile/wiki/Defects), check it out it's very easy to add new items/edit. Also comes with a large amount of markdown options.

Also didn't venom work like Magic, where if you get x amount you die immediately?

**Comment by RVNJ** [comment]
All effects as of yet are described here
