### ISSUE TITLE
Attributes delete themselves???

### ISSUE THREAD

**Issue by RVNJ** [phoenixanimations/TheNuwasFile#54]
Fuck

have to revert update

**Comment by RVNJ** [comment]
Hotfixed. Will need a more in-depth fix later.

**Comment by phoenixanimations** [comment]
Gonna leave this open, as I intend to fix it. 

See if the sorting code ever does this:

```csharp
object foo;
object bar;
foo = bar;
bar = foo;

```

But see what happens when that's done in a list.
```csharp
list.Add(foo);
list.Add(bar);
list[0] = bar;
list[1] = foo;
```

**Comment by RVNJ** [comment]
think it done

**Comment by phoenixanimations** [comment]
Issue was caused by equipping -> then deleting an attribute on the equipped character. Unity didn't know what the reference was but the data was still on the file.
