### ISSUE TITLE
Do some tests in equipping-deletes-attributes branch.

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#65]
+ [ ] Add an attribute to character sheet -> equip -> sort.
+ [ ] Equip -> add an attribute to character sheet -> sort.
+ [ ] Equip multiple weapons then sort.
+ [ ] _Equip Secondary and/or Shield and/or Armor -> sort_
+ [ ] Dup attribute of weapon -> change spell speed -> Equip -> sort -> Unequip.
+ [ ] Add attribute to weapon -> Equip -> sort -> Unequip.

That's all the ideas I haven't tested for now.

**Comment by phoenixanimations** [comment]
If you want to retest some of mine:

+ [ ] Equip -> Sort.
+ [ ] Equip -> Unequip -> Sort
+ [ ] Equip x 2 -> Unequip x 4 -> Sort

**Comment by RVNJ** [comment]
first 3 tested, need duplicate and delete buttons unhidden to continue

**Comment by RVNJ** [comment]
we good, we good
