### ISSUE TITLE
What to do about healing vs negative damage/resistance

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#75]
Not a top priority but eventually we should figure out if it _should_  be possible to do negative damage, and how negative resistance should work.

**Comment by RVNJ** [comment]
if (Damage > 0){
Damage *= -1
} else {
[nothing happens]
}

**Comment by phoenixanimations** [comment]
What about negative resistance?

**Comment by RVNJ** [comment]
I actually have to check for that one but I believe it would also invert Damage (from what I remember of when I was adding it)

I don't **think** we'll end up using negative Resistance but it is something to account for since it directly affects/modifies your Damage.

**Comment by RVNJ** [comment]
based on the way the nodes work for Resistance, it should indeed invert Damage to heal, so it's something we *can* use but likely something we *won't* use.
