### ISSUE TITLE
Short-Term Passives to be Added

### ISSUE THREAD

**Issue by RVNJ** [phoenixanimations/TheNuwasFile#78]
**Soon**
- [x] Conservation (no attacks made) (swap in Unity, those are wrong)
- [x] Preservation (steal Active energy) (swap in Unity, those are wrong)
- [x] 'Reroll' Shield
- [x] Hammer Shield
- [x] Survival Shield

**Later**
- [x] Inspiration
- [x] Quick-Draw

```
Inspiration (x10)
D1 + 0.1
A1 + 0.05

Quickdraw (x3)
D2 + 0.05
A2 - 0.05

2.15x	|	(D1 + D2) = ((1) + 1.15) [10]	|	[0 + 10 + 1.5 = 11.5](0.1)
1.35x	|	(A1 + A2) = ((1) + 0.35) [3]	|	[0 + 10 - 3 = 7](0.05)
```

I promise this makes sense

**Comment by RVNJ** [comment]
Continuation from #62

**Comment by RVNJ** [comment]
I can do all of these today.

**Comment by phoenixanimations** [comment]
Sweet, for the survival shield does it extend your death or is that armor? 

If it does just add a death attribute to the player, and the armor will simply make that state "none" until turn three. I suggest making it attach a `status` something like:

Character Sheet `Player`
+ Attribute `Death` [Begin of Turn]: If hitpoint < 0 debug "died"

Weapon:
+ Attribute `Assign Survival` [End Turn]: If hitpoint < 0 equip `Survival Status`

Survival Status:
+ Stat `Turn Count`: 1
+ Attribute [Begin of Turn]: Add 1 to `Turn Count`
+ Attribute [Begin of Turn]: If turn count < 3 turn off `Death`.

**Comment by phoenixanimations** [comment]
But if you have another way of doing it by all means.

**Comment by RVNJ** [comment]
That's Enduring - Survival will simply check before and after 'Apply Damage' (Enemy turn) to see if your Current Hitpoints dropped to 0 from above >=20%, if it did, you 'revive' with 20% Hitpoints remaining. That is probably how I'll do Enduring though, yeah.

I'm holding off on finishing up Inspiration & QuickDraw (as well as Survival) today because I did the thing we mentioned earlier, partitioning the Attributes and Passive effects. Everything has been restructured to use the new system, so feel free to take a look. I'm not sure if having these things equipped will bug the 'dup/delete' buttons but if so, I'll just remove them on a case-to-case basis, since it doesn't seem like we'll need to change much if anything on weapons without directly modifying the Passives/Actives Attached/Equipped to them (if that makes any sense?).

Anyway, I still have to go through and move Shield Attributes off to new sheets (just remembered) - there may also be an armor or two that have Attributes on them that could do with moving to a new Sheet to re-attach them.

but yeah, looking promising so far - hopefully we'll be able to run some tests sometime in the near future

**Comment by phoenixanimations** [comment]
Awesome, glad to here that! I checked on the commit and ya super cool. The dup attributes should not glitch. 

I'll take a closer look at how you separated them, but I'm thinking this is going to be the new structure of the file.

**Comment by RVNJ** [comment]
> I can do all of these today.

but ya didn't, did ya
