### ISSUE TITLE
Find the inventory/equip bug (Grimlash related?)

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#84]
Over the phone you mentioned a bug where you equipped Grimlash with an active. Lets try to reproduce this bug.

I have tried:
1. Equipping and unequipping. 

No bug on my end.

I have noticed:
1. Go to Grimlash
2. Right Click -> Debug
3. Make the equipment list amount: 3
4. Delete the third item on the list
5. Right Click -> Normal

It will show an error. This is because there is nothing equipped (forgot to check for null here). Do you think this is how you got the error?

**Comment by RVNJ** [comment]
Will probably have to explain over Skype

**Comment by RVNJ** [comment]
I think we did this, yeah
